# Generated by Django 5.1 on 2024-08-28 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=30)),
                ('tributare_type_id', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('P', 'Pasaporte'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('NIUP', 'NIUP')], default='CC', max_length=5, verbose_name='Tipo de Identificación Tributaria')),
                ('id_number', models.CharField(max_length=15)),
                ('corporate_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('regime_type', models.CharField(choices=[('IVA', 'Responsable de IVA'), ('No IVA', 'Responsable de NO IVA')], default='IVA', max_length=7, verbose_name='Tipo de regimen')),
                ('taxpayer_type', models.CharField(choices=[('Juridico', 'Pesona juridica'), ('Natural', 'Pesona natural')], default='IVA', max_length=10, verbose_name='Tipo de contribuyente')),
                ('tax_liability', models.CharField(choices=[('01', 'IVA impuesto sobre las ventas'), ('04', 'INC impuesto nacional al consumo'), ('ZA', 'IVA - INC'), ('ZZ', 'No aplica')], default='IVA', max_length=3, verbose_name='Responsabilidad tributaria')),
                ('tax_id_type', models.CharField(choices=[('01', 'Gran contribuyente'), ('02', 'Autorretenedor'), ('03', 'Agente de retencion en el impuesto sobre las ventas'), ('04', 'Regimen simple de tributacion'), ('05', 'R-99-PN'), ('06', 'No aplica'), ('07', 'Otros')], default='IVA', max_length=55, verbose_name='Tipo de identificacion tributaria')),
                ('eEmail', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('eEmail', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contactos', to='Clientes.client')),
            ],
        ),
    ]
