# Generated by Django 5.1 on 2024-10-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Complementos', '0002_remove_complements_client'),
        ('Servicios', '0003_remove_services_url_services_cateogry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.services')),
            ],
        ),
        migrations.CreateModel(
            name='ClientComplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client')),
                ('complement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Complementos.complements')),
            ],
            options={
                'unique_together': {('client', 'complement')},
            },
        ),
    ]
