# Generated by Django 5.1 on 2024-10-21 22:35

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientservice_clientcomplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 20, 22, 35, 42, 507041, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientservice',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
