# Generated by Django 5.1 on 2024-10-21 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_clientservice_expirationdate_clientservice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 20, 23, 34, 30, 371549, tzinfo=datetime.timezone.utc)),
        ),
    ]
