# Generated by Django 5.1 on 2024-10-22 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_clientservice_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 2, 21, 37, 273403, tzinfo=datetime.timezone.utc)),
        ),
    ]
