# Generated by Django 5.1 on 2024-10-23 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_alter_clientservice_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 22, 21, 20, 48, 674001, tzinfo=datetime.timezone.utc)),
        ),
    ]
