# Generated by Django 5.1 on 2024-10-24 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_alter_clientservice_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 1, 23, 13, 879864, tzinfo=datetime.timezone.utc)),
        ),
    ]
