# Generated by Django 5.1 on 2024-10-24 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0013_alter_clientservice_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 2, 41, 34, 7937, tzinfo=datetime.timezone.utc)),
        ),
    ]
