# Generated by Django 5.1 on 2024-10-25 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0014_alter_clientservice_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='expirationDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 24, 4, 40, 41, 696846, tzinfo=datetime.timezone.utc)),
        ),
    ]
