# Generated by Django 5.1 on 2024-10-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='client',
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.services')),
            ],
        ),
    ]
