# Generated by Django 5.1 on 2024-10-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_remove_services_client_clientservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='url',
        ),
        migrations.AddField(
            model_name='services',
            name='cateogry',
            field=models.CharField(choices=[('OK', 'OK Web'), ('Comp', 'Complemento'), ('Cons', 'Constructor')], default='OK', max_length=12, verbose_name='Categoria del servicio'),
        ),
        migrations.DeleteModel(
            name='ClientService',
        ),
    ]
