# Generated by Django 5.1 on 2024-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_rename_cateogry_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('OK Web', 'OK Web'), ('Complemento', 'Complemento'), ('Constructor', 'Constructor')], default='OK', max_length=12, verbose_name='Categoria del servicio'),
        ),
    ]
