# Generated by Django 5.1 on 2024-10-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_alter_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Ok Web', 'Ok Web'), ('Complemento', 'Complemento'), ('Constructor', 'Constructor')], default='OK', max_length=12, verbose_name='Categoria del servicio'),
        ),
    ]
