# Generated by Django 5.1 on 2024-10-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='color',
            new_name='priority',
        ),
    ]
